# Generated by Django 3.1.8 on 2021-06-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210601_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
